server:
  port: 30001
spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false&userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.kdyzm: debug
    web: debug
    sql: debug
    root: warn